### ISSUE TITLE
TypeScript 3.0 support?

### ISSUE THREAD

**Issue by dsherret** [cevek/ttypescript#21]
I tried upgrading to `typescript@rc` and I'm getting this error with ttypescript 1.4.6 (works fine when just running tsc):

```ts
> ttsc
V:\ts-simple-ast\node_modules\typescript\lib\tsc.js:113686
})(ts || (ts = {}));
^

SyntaxError: Unexpected token }
    at Object.<anonymous> (C:\Users\david\AppData\Roaming\npm\node_modules\ttypescript\lib\tsc.js:26:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\david\AppData\Roaming\npm\node_modules\ttypescript\bin\tsc:2:1)
    at Module._compile (module.js:652:30)
```

Any ideas? Sorry, I tried to look into it a bit but gave up.

**Comment by dsherret** [comment]
@cevek do you have the time to publish it? TS 3.0 was released today.

**Comment by cevek** [comment]
@dsherret done
ttypescript@1.5.2

**Comment by dsherret** [comment]
@cevek thanks a lot!
