### ISSUE TITLE
Seems not working with ts-node

### ISSUE THREAD

**Issue by DavidBabel** [cevek/ttypescript#43]
Hey there, 

I'm trying to bootstrap a project with your tool, and i got an issue to make this "plugin" work with ts-node.

Here is a reproductible repository : https://github.com/DavidBabel/test
```bash
git clone git@github.com:DavidBabel/test.git
cd test
yarn install && yarn start
```

Here is the error : 
```bash
/Users/david/dev-others/project-score/src/main/score.ts:1
(function (exports, require, module, __filename, __dirname) { export const scores = {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:694:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

I do not know if it's related to https://github.com/cevek/ttypescript or the plugin https://github.com/grrowl/ts-transformer-imports

Fun part, it works well if i use ts-node-dev instead of ts-node.

**Comment by cevek** [comment]
I've debugged it, so this is bug from ts-transformer-imports
this lines
https://github.com/grrowl/ts-transformer-imports/blob/master/transformer.ts#L7
disable transforming files by ts-node, so node.js try to perform ts files like js files.

**Comment by cevek** [comment]
try this one
https://github.com/zerkalica/zerollup/tree/master/packages/ts-transform-paths

**Comment by DavidBabel** [comment]
Thanks mate !

Amazing tool by the way.
