### ISSUE TITLE
Cannot read property 'length' of undefined after updating

### ISSUE THREAD

**Issue by mflux** [cevek/ttypescript#72]
I'm getting this:

```
C:\Users\Flux\Documents\projects\voronoi\node_modules\typescript\lib\tsc.js:247
        if (commandLineArgs.length > 0 && commandLineArgs[0].charCodeAt(0) === 45 /* minus */) {
                            ^

TypeError: Cannot read property 'length' of undefined
    at isBuild (C:\Users\Flux\Documents\projects\voronoi\node_modules\typescript\lib\tsc.js:247:29)
    at Object.executeCommandLine (C:\Users\Flux\Documents\projects\voronoi\node_modules\typescript\lib\tsc.js:255:13)
    at Object.<anonymous> (C:\Users\Flux\Documents\projects\voronoi\node_modules\ttypescript\lib\tsc.js:15:4)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Flux\Documents\projects\voronoi\node_modules\ttypescript\bin\tsc:2:1)
```

Running this:

```npx ttsc --project tsconfig.json -w```

While having these versions:

```  
  "devDependencies": {
    "@types/jasmine": "^3.5.0",
    "@zoltu/typescript-transformer-append-js-extension": "^1.0.1",
    "jasmine": "^3.5.0",
    "ts-node": "^8.5.4",
    "ttypescript": "^1.5.8",
    "typescript": "^3.7.2"
  }
```

Is the latest version broken?

**Comment by nonara** [comment]
TS 3.7 changed the structure a bit of tsc which breaks ttypescript code. It looks like it should have been addressed in ttypescript v1.5.8. Try reinstalling and making sure you have 1.5.8.

I'm not sure how much support this repository is getting any more. You're welcome to try [ts-patch](http://www.npmjs.com/ts-patch/) if it doesn't work for you. It was based on ttypescript

**Comment by cevek** [comment]
@mflux Can you provide repro project? ttypescript works fine with ts 3.7

**Comment by mflux** [comment]
Looks like I had outdated typescript installed in global packages. Thanks all.

**Comment by mflux** [comment]
Here is what I'm trying to run

https://github.com/mflux/voronoi

**Comment by cevek** [comment]
Have you tried running it from scratch? 
For me everything compiled fine

**Comment by mflux** [comment]
Thanks, I got it working from scratch. Had to delete all my global npm packages.
