### ISSUE TITLE
[QUESTION] Having troubles that end up with error "Can not read property flags of undefined"

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [cevek/ttypescript#77]
Here is my code

```typescript
export default function(program: ts.Program, pluginOptions: {}) {
    return (ctx: ts.TransformationContext) => {
        return (sourceFile: ts.SourceFile) => {

            let found: Boolean = false;
            function visitor(node: ts.Node): ts.Node {
                // Logic for finding something in code
                found = true;
                return ts.visitEachChild(node, visitor, ctx);
            }

            ts.visitEachChild(sourceFile, visitor, ctx);
            if (found) {
                const newCodeAsText = `
                    import * as path from 'path';
                    export default something = "Some code that should be used instead of original one";
                `;
                const newSourceFile = ts.createSourceFile(sourceFile.fileName, newCodeAsText, sourceFile.languageVersion, true, ts.ScriptKind.TS ); 

                const printer: ts.Printer = ts.createPrinter({
                    newLine: ts.NewLineKind.LineFeed
                });

                console.log('===========================');
                console.log(printer.printFile(newSourceFile));
    
                return newSourceFile; 
            }


            return sourceFile; // return original file if didn't find what looking for
        };
    };
}
```

Found out that responsible for this error is 
```
import * as path from 'path'
```

Any import in code as string is causing that mentioned error (detailed error below). Don't know if it is a bug or if I should do something more to get it working?

```
Cannot read property 'flags' of undefined
    at getSymbolLinks (/home/daniel/Dokumenty/Programowanie/my-frameworks/ts-mini-manager2/node_modules/typescript/lib/typescript.js:34099:24)
    at isReferencedAliasDeclaration (/home/daniel/Dokumenty/Programowanie/my-frameworks/ts-mini-manager2/node_modules/typescript/lib/typescript.js:64075:30)
    at Object.isReferencedAliasDeclaration (/home/daniel/Dokumenty/Programowanie/my-frameworks/ts-mini-manager2/node_modules/typescript/lib/typescript.js:64353:35)
    at visitNamedImportBindings (/home/daniel/Dokumenty/Programowanie/my-frameworks/ts-mini-manager2/node_modules/typescript/lib/typescript.js:75545:33)
    at Object.visitNode (/home/daniel/Dokumenty/Programowanie/my-frameworks/ts-mini-manager2/node_modules/typescript/lib/typescript.js:70939:23)
    at visitImportClause (/home/daniel/Dokumenty/Programowanie/my-frameworks/ts-mini-manager2/node_modules/typescript/lib/typescript.js:75534:36)
    at Object.visitNode (/home/daniel/Dokumenty/Programowanie/my-frameworks/ts-mini-manager2/node_modules/typescript/lib/typescript.js:70939:23)
    at visitImportDeclaration (/home/daniel/Dokumenty/Programowanie/my-frameworks/ts-mini-manager2/node_modules/typescript/lib/typescript.js:75519:35)
    at visitEllidableStatement (/home/daniel/Dokumenty/Programowanie/my-frameworks/ts-mini-manager2/node_modules/typescript/lib/typescript.js:73506:28)
    at sourceElementVisitorWorker (/home/daniel/Dokumenty/Programowanie/my-frameworks/ts-mini-manager2/node_modules/typescript/lib/typescript.js:73485:28)
error Command failed with exit code 1.
```

**Comment by cevek** [comment]
I think the problem is that typescript try to understand what import type is using. Because syntacticly impossible to check that `path` is real variable/class/function or interface/type. All types and interfaces will be removed by native es6 transformer. This transformer uses typechecker information, stored into `flags` field in each ast node to check real meaning of this import. 
So, try create this ast nodes by hand. Maybe it will help you

**Comment by cevek** [comment]
see https://github.com/microsoft/TypeScript/pull/35200

**Comment by DanielMazurkiewicz** [comment]
@cevek Thanks!
