### ISSUE TITLE
EACCES bug with tsc-watch

### ISSUE THREAD

**Issue by n8jadams** [cevek/ttypescript#88]
My npm script in package.json:
```json
{
"dev:server": "tsc-watch --noClear --compiler ttypescript/bin/tsc -p server/tsconfig.json --outDir dist/server --onSuccess \"node server/server.ts\""
}
```

The output when I run `npm run dev:server`
```
Error: spawn /Users/nateadams/oss/aws-s3-svg-cms/node_modules/ttypescript/lib/typescript.js EACCES
at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

I had to run `chmod -R u+x /my/project/folder/node_modules` to fix it. Seems kind of weird that I would run into permission problems, I didn't tamper with any permissions, just used things how npm intends...

(I'm running on MacOS btw)

**Comment by n8jadams** [comment]
I'm closing this as I can't really replicate it, nuking my whole repo, cloning again, reinstalling node_modules etc fixed it...
